# src/oragent/solution_database.py
"""
# Solution Database

This solution database is a re-implementation of FunSearch's `ProgramsDatabase`.
Original paper:
 - Romera-Paredes, B., Barekatain, M., Novikov, A., Balog, M., Kumar, M.P., Dupont, E., Ruiz, F.J., Ellenberg, J.S., Wang, P., Fawzi, O. and Kohli, P., 2024. Mathematical discoveries from program search with large language models
Original code:
 - https://github.com/google-deepmind/funsearch/tree/main



## Overview
Solution database is the database to manage the generated solutions.
`Solution` dataclass fields that will be used by the database:
- `features` (Tuple[int, ...]): Feature vector of the solution, used by the MAP-Elites-based solution database for indexing. Generated by the Evaluator. Default: `None`.
- `score` (float): Overall score of the solution. Generated by the Evaluator. Default: `None`.
- `island_id` (int): The ID of the island where the solution was found. Default: `None`.

Only one database is created for the project runtime; all lead agents share the same database.
Each lead agent starts one research round by sampling several (default: two) solutions from the database.
Island-based & MAP-Elites-based models are used to manage the database.



## How It Works
The database is organized into multiple islands, each evolving independently. 
Islands with lower average scores are periodically reset to maintain population quality.
Each island contains clusters of solutions, where each cluster groups solutions sharing identical features. 
The score measures a solution's fitness, and `obj_type` ("max" or "min") in configuration file determines whether higher or lower scores are preferred.

Database sampling process (to sample `k` solutions):
    1. Uniformly sample one island at random from all available islands
    2. Sample `k` clusters from the selected island; each cluster's selection probability is proportional to its score
        Note: Sampling is performed without replacement to avoid repetition, ensuring parent solutions for lead agents are unique
    3. Sample one function from each selected cluster, favoring shorter programs; each function's selection probability is inversely proportional to its length

Adding solutions to the database:
    Island assignment: New solutions generated from an island are automatically added back to that same island
    Cluster assignment: Determined by the solution's features value (see below)



## About Solution features
The features of a solution is a tuple of integers that characterizes the solution's profile.
In the original FunSearch paper, this concept is called "signature" and represents the tuple of scores a program achieves across different test inputs.
Concrete example (Cap Set Problem):
    Test inputs: dimensions n = 3, 4, 5, 6, 7, 8
    Program A finds cap sets of sizes: [9, 20, 45, 112, 236, 496]
    -> Signature: (9, 20, 45, 112, 236, 496)
    Program B finds cap sets of sizes: [9, 20, 45, 112, 236, 512]
    -> Signature: (9, 20, 45, 112, 236, 512)

In this implementation, we don't restrict how features should be formulated. Users can customize the feature computation in the `eval.py` file. 
Typically, feature elements represent different aspects of solution performance, plus additional attributes like categorized code length.

### Cluster mechanics:
    Programs with identical features_list belong to the same cluster When a program has a new signature, a new cluster is created for it
    This signature-based clustering implements the MAP-Elites algorithm

### Important notes
Avoid using full-precision floating-point numbers as feature values, as this would result in each cluster containing only one solution.
If a solution's features is None, a dedicated cluster containing only that solution is created.
If all solutions have None features, MAP-Elites is effectively disabled.




## About sampling temperature
We normalize scores before sampling. Two places where you need to set sampling temperature:

1) Island sampling cluster involves `cluster_sampling_temperature_init` and `cluster_sampling_temperature_period` config parameters
```
cluster_scores = np.array([self._clusters[features].score for features in features_list])
cluster_scores_normalized = (cluster_scores - min(cluster_scores)) / (max(cluster_scores) + 1e-6)
period = self.cluster_sampling_temperature_period
temperature = self.cluster_sampling_temperature_init * (1 - (self._num_programs % period) / period)
probabilities = _softmax(cluster_scores_normalized, temperature) if self.obj_type == 'max' else _softmax(-cluster_scores_normalized, temperature)
````
`cluster_scores_normalized` is in range (0, 1)

2) Cluster sampling solutions also involves a temperature setting
```
normalized_lengths = (np.array(self._lengths) - min(self._lengths)) / (max(self._lengths) + 1e-6)
probabilities = _softmax(-normalized_lengths, temperature=1.0)
```
`normalized_lengths` is in range (0, 1)

### Testing `_softmax`
The following tests are intended to help you to get a feeling about how to set the temperature:
==============
20 logits randomly sampled from [0, 1]:
Logits: [0.97 0.95 0.87 0.83 0.73 0.71 0.6  0.6  0.52 0.43 0.37 0.3  0.29 0.21 0.18 0.18 0.16 0.16 0.06 0.02]
--------------
Temperature: 0.1
Probabilities: [0.37 0.31 0.13 0.09 0.03 0.03 0.01 0.01 0.   0.   0.   0.   0.  0.  0.   0.   0.   0.   0.   0.  ]
--------------
Temperature: 0.2
Probabilities: [0.23 0.21 0.14 0.12 0.07 0.06 0.04 0.04 0.03 0.02 0.01 0.01 0.01 0.01 0.   0.   0.   0.   0.   0.  ]
--------------
Temperature: 0.5
Probabilities: [0.12 0.11 0.09 0.09 0.07 0.07 0.06 0.06 0.05 0.04 0.04 0.03 0.03 0.03 0.02 0.02 0.02 0.02 0.02 0.02]
--------------
Temperature: 1.0
Probabilities: [0.08 0.08 0.07 0.07 0.06 0.06 0.06 0.05 0.05 0.05 0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.03 0.03]
==============
 


## What the script contains:
Three classes for storing solutions:
 - `SolutionDatabase`: A database of solutions.
 - `Island`: A sub-population of the solution database.
 - `Cluster`: A cluster of solutions on the same island and with the same feature.
Internal utility functions:
- `_softmax`: Computes the softmax of a set of logits with a temperature parameter. Called when sampling.
"""
import os
import sys
import time
from typing import Any, Union, Tuple, Dict, List
import numpy as np
from pathlib import Path
import scipy
import json
import yaml
import random
from dataclasses import asdict
from copy import deepcopy
import numpy as np
import oragent.utils as utils
from oragent.utils import Solution



class NumpyEncoder(json.JSONEncoder):
    """
    Dict marshaler for JSON serialization.
    Solution may contains numpy arrays. Use this encoder for serializing the solution dict before json.dump().
    """
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        return super().default(obj)
    
    
# Internal functions used for sampling
def _softmax(logits: Union[np.ndarray, list], temperature: float) -> np.ndarray:
    """
    Returns the tempered softmax of 1D finite `logits`.
    Used to sample from clusters within an island, and to sample programs within a cluster.
    Cf. FunSearch, p9
    When sampling a cluster, we favour those with larger score values.
    When sampling a program within a cluster, we favour shorter programs.
    
    Args:
        logits: 1D array of logits.
        temperature: Temperature parameter.
    
    Returns:
        1D array of probabilities.
    """
    if isinstance(logits, List):
        logits = np.asarray(logits, dtype=np.float32)
        
    if not np.all(np.isfinite(logits)):
        non_finites = set(logits[~np.isfinite(logits)])
        raise ValueError(f'`logits` contains non-finite value(s): {non_finites}')
    
    if not np.issubdtype(logits.dtype, np.floating):
        logits = np.array(logits, dtype=np.float32)

    result = scipy.special.softmax(logits / temperature, axis=-1)

    # Ensure that probabilities sum to 1 to prevent error in `np.random.choice`.
    index = np.argmax(result)
    result[index] = 1 - np.sum(result[0:index]) - np.sum(result[index+1:])
    return result




class SolutionDatabase:
    """
    A collection of solutions, organized as islands.
    """
    def __init__(self, checkpoint=None, config=None) -> None:
        # =====General configuration start (common for all agents)=====
        self.package_dir = Path(__file__).parent
        self.project_root = Path.cwd()
        # Problem data is stored in `<project_root>/problems`
        # Prompts are stored in `<project_root>/prompts`
        
        if checkpoint:  # if checkpoint specified, load checkpoint
            self.load(checkpoint=checkpoint)
        elif config:  # else, check if config is provided
            self.config = config
        else:  # else, use default config
            # Load built-in config if config is not provided
            with open(f'{self.package_dir}/config.yaml', 'r') as f:
                self.config = yaml.safe_load(f)
                
        self.algorithm = self.config['algorithm'].lower().strip()
        self.problem = self.config['problem'].lower().strip()  # the problem to solve
        # Load experiment config if not provided
        if 'experiment' not in self.config:
            experiment_config_path = self.project_root / "problems" / self.problem / "settings.yaml"
            with open(experiment_config_path, 'r') as f:
                experiment_config = yaml.safe_load(f)
            self.config['experiment'] = experiment_config
        # Experiment config
        self.function_to_evolve = self.config['experiment']['function_to_evolve']  # the name of the function to be evolved
        self.obj_type = self.config['experiment']['obj_type'].lower().strip()
        assert self.obj_type in ['max', 'min'], f"Invalid objective type: {self.obj_type}"
        
        # =====SolutionDatabase settings=====
        self.reset_period_minutes = self.config["database"]["reset_period_minutes"]
        self.num_islands = self.config['database']['num_islands']
        self.num_parents = self.config['num_parents']
        
        # =====Vars updated during agent running=====
        # if no checkpoint specified, we need to create them
        if not checkpoint:
            # Initialize empty islands
            self._islands: list[Island] = []
            for i in range(self.num_islands):
                # Loop to initialize islands.
                self._islands.append(Island(self.config, island_id=i))
            # Best solution and its score per island.
            self._best_score_per_island: list[float] = [-float('inf')] * self.num_islands if self.obj_type == 'max' else [float('inf')] * self.num_islands
            # Best scores per test per island.
            self._best_solution_per_island = [None] * self.num_islands
            # Time of the last island reset.
            self._last_reset_time: float = time.time()
    
    def __len__(self):
        """The total number of solutions in the solution database.
        Note: repetitions may exist due to database initialization and island reset."""
        total = 0
        for island in self._islands:
            for cluster in island._clusters.values():
                total += len(cluster._solutions)
        return total
    
    
    def get_best(self):
        """Get the best solution of the database."""
        # find the best solution of all islands then return it; make use of self._best_score_per_island and self._best_solution_per_island
        if self.obj_type == 'max':
            best_island_idx = np.argmax(self._best_score_per_island)
        else:  # 'min'
            best_island_idx = np.argmin(self._best_score_per_island)

        return self._best_solution_per_island[best_island_idx]
    
    def sample(self, num_parents=None):
        """Draw samples from the database."""
        num_parents = num_parents or self.num_parents
        
        # Choose an island uniformly at random.
        island_id = np.random.randint(len(self._islands))
        
        # Sample from the island.
        samples = self._islands[island_id].sample(num_parents)
        
        return samples


    def _add_solution_to_island(self, solution: Solution) -> None:
        """Add a solution to a specified island."""
        island_id = solution.island_id
        
        self._islands[island_id].add(solution)
        
        if (self.obj_type == 'max' and solution.score > self._best_score_per_island[island_id]) \
            or (self.obj_type == 'min' and solution.score < self._best_score_per_island[island_id]):  # if program score is better than current best
            self._best_solution_per_island[island_id] = solution
            self._best_score_per_island[island_id] = solution.score
            print(f'\n>>>[Database] Best score of island {island_id} changed to {solution.score}')
            # log the best program found
            #timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            #output_file = f"{self.project_root}/outputs/{self.algorithm}/{self.problem}/best_solution_{solution.id_str(self.algorithm)}.json"
            #with open(output_file, 'w') as f:
            #    json.dump(asdict(solution), f, indent=4, cls=NumpyEncoder)
        
    def add_solution(self, solution: Solution) -> None:
        """Add a solution to the database."""        
        # Log newly obtained solution to the text file
        #timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        #output_file = f"{self.project_root}/outputs/{self.algorithm}/{self.problem}/solution_{solution.id_str(self.algorithm)}.json"
        #with open(output_file, 'w') as f:
        #    json.dump(asdict(solution), f, indent=4, cls=NumpyEncoder)
        
        if solution.island_id is None:
            # If island_id is None, this is a program added at the beginning, so adding it to ALL islands.
            for island_id in range(len(self._islands)):
                # we will need to change the island_id of solution; make a deepcopy before changing
                sol_copy = deepcopy(solution)
                sol_copy.island_id = island_id
                self._add_solution_to_island(sol_copy)
        else:
            self._add_solution_to_island(solution)

        # Check whether it is time to reset an island.
        if time.time() - self._last_reset_time > self.reset_period_minutes * 60:
            self._last_reset_time = time.time()
            self.reset_islands()

    def add(self, solutions: Union[Solution, List[Solution]]) -> None:
        """Add a solution or a list of solutions to the database."""
        if not solutions:
            return
            
        if not isinstance(solutions, List):
            solutions = [solutions]
            
        for sol in solutions:
            self.add_solution(sol)
    
    
    def reset_islands(self) -> None:
        """
        Resets the weaker half of islands.
        
        Cf. Funsearch, paper, p9:
        Every 4h, we discard all the programs from the m/2 islands whose best instances have the lowest score. Each of these islands is
        then seeded with a single program, obtained by first choosing one of the surviving m/2 islands uniformly at random and then retrieving the
        highest-scoring program from that island (breaking ties in favour of older programs). The evolutionary process is then restarted from this
        state, in which the reset islands contain one high-performing program each (Extended Data Fig. 2).
        """
        # We sort best scores after adding minor noise to break ties.
        # np.argsort returns an array of integers representing the indices
        # np.argsort is ascending by default; smaller scores come first; small score islands are to be reset
        indices_sorted_by_score: np.ndarray = np.argsort(self._best_score_per_island + np.random.randn(len(self._best_score_per_island)) * 1e-6)
        if self.obj_type == 'min':
            indices_sorted_by_score = indices_sorted_by_score[::-1]  # reverse for 'min' objective
        num_islands_to_reset = self.num_islands // 2
        reset_islands_ids = indices_sorted_by_score[:num_islands_to_reset]  # the first half (with lowest scores) islands to reset
        keep_islands_ids = indices_sorted_by_score[num_islands_to_reset:]
        for island_id in reset_islands_ids:
            # Create a new island instance
            self._islands[island_id] = Island(self.config, island_id=island_id)
            self._best_score_per_island[island_id] = -float('inf') if self.obj_type == 'max' else float('inf')
            # Randomly choose a founder from the surviving islands to ignite the reset island
            # Note: for each island to reset, we randomly choose a founder independently
            founder_island_id = np.random.choice(keep_islands_ids)  # sample one island to keep
            # Make a deep copy of the founder solution to avoid interference; and remember to set the island_id
            founder_solution = deepcopy(self._best_solution_per_island[founder_island_id])
            founder_solution.island_id = island_id
            self._add_solution_to_island(founder_solution)


    def visualize(self, file=sys.stdout) -> None:
        """Summarize and visualize the solution database.
        
        Example:
========================================
SOLUTION DATABASE VISUALIZATION
========================================
Total islands: 2
Objective type: max

ISLAND 0:
  Number of clusters: 2
  Total solutions: 3
  Best score in island: 0.9

  CLUSTER 0:
    Features: (1, 2, 3)
    Cluster score: 0.800000
    Number of solutions: 2
      Solution 0:
        Score: 0.700000
        Code length: 21
        ID: 1

      Solution 1:
        ...

  CLUSTER 1:
    ...

----------------------------------------
ISLAND 1:
    ...

----------------------------------------

SUMMARY STATISTICS:
Total solutions across all islands: 4
Total clusters across all islands: 3
Average cluster size: 1.33
Best overall score: 0.900000 (Island 0)
========================================
        """
        print("=" * 40, file=file)
        print("SOLUTION DATABASE VISUALIZATION", file=file)
        print("=" * 40, file=file)
        print(f"Total islands: {len(self._islands)}", file=file)
        print(f"Objective type: {self.obj_type}", file=file)
        print(file=file)

        for island_idx, island in enumerate(self._islands):
            print(f"ISLAND {island_idx}:", file=file)
            print(f"  Number of clusters: {len(island._clusters)}", file=file)
            print(f"  Total solutions: {island._num_programs}", file=file)
            print(f"  Best score in island: {self._best_score_per_island[island_idx]}", file=file)
            print(file=file)

            # Display clusters in this island
            for cluster_idx, (features, cluster) in enumerate(island._clusters.items()):
                print(f"  CLUSTER {cluster_idx}:", file=file)
                print(f"    Features: {features}", file=file)
                print(f"    Cluster score: {cluster._score:.6f}", file=file)
                print(f"    Number of solutions: {len(cluster._solutions)}", file=file)

                # Display solutions in this cluster
                for sol_idx, solution in enumerate(cluster._solutions):
                    print(f"      Solution {sol_idx}:", file=file)
                    print(f"        Score: {solution.score:.6f}", file=file)
                    print(f"        Code length: {len(solution.code)}", file=file)
                    if hasattr(solution, 'id') and solution.id is not None:
                        print(f"        ID: {solution.id}", file=file)
                    print(file=file)

            print("-" * 40, file=file)

        # Summary statistics
        print("\nSUMMARY STATISTICS:", file=file)
        total_solutions = sum(island._num_programs for island in self._islands)
        total_clusters = sum(len(island._clusters) for island in self._islands)
        print(f"Total solutions across all islands: {total_solutions}", file=file)
        print(f"Total clusters across all islands: {total_clusters}", file=file)

        if total_solutions > 0:
            avg_cluster_size = total_solutions / total_clusters if total_clusters > 0 else 0
            print(f"Average cluster size: {avg_cluster_size:.2f}", file=file)

        # Best solution overall
        if self.obj_type == 'max':
            best_island_idx = np.argmax(self._best_score_per_island)
            best_score = max(self._best_score_per_island)
        else:
            best_island_idx = np.argmin(self._best_score_per_island)
            best_score = min(self._best_score_per_island)

        print(f"Best overall score: {best_score:.6f} (Island {best_island_idx})", file=file)
        print("=" * 40, file=file)


    def save(self, checkpoint: str):
        """
        Save the solution database data to a JSON file.
        """
        # No need to save config data since we will always require user to input config file to create SolutionDatabase instance.
        # all variables that can be inferred from the config file need NOT to be saved.
        checkpoint_directory = f'{self.project_root}/checkpoints/{checkpoint}'
        database_path = os.path.join(checkpoint_directory, 'database.json')
        
        # No need to save config file since agent will save it
        
        # Prepare data to save
        save_data = {
            "last_reset_time": self._last_reset_time,
            "islands": [],
            "best_score_per_island": self._best_score_per_island,
            "best_solution_per_island": [],
        }

        # Save best solutions per island
        for solution in self._best_solution_per_island:
            if solution is None:
                save_data["best_solution_per_island"].append(None)
            else:
                save_data["best_solution_per_island"].append(asdict(solution))

        # Save island data
        for island in self._islands:
            island_data = {
                "island_id": island.island_id,
                "num_programs": island._num_programs,
                "clusters": {}
            }

            # Save cluster data for this island
            for features, cluster in island._clusters.items():
                cluster_data = {
                    "score": cluster._score,
                    "solutions": [asdict(sol) for sol in cluster._solutions],
                    "lengths": cluster._lengths
                }
                # Convert features tuple to string for JSON serialization
                features_key = str(features) if features is not None else "None"
                island_data["clusters"][features_key] = cluster_data

            save_data["islands"].append(island_data)

        # Save to file
        with open(database_path, 'w') as f:
            json.dump(save_data, f, indent=4, cls=NumpyEncoder)
            
    def load(self, checkpoint: str):
        """Load the solution database data from a JSON file."""
        # Usage: users will first create SolutionDatabase instance then call this load method.
        # Note: all variables that can be inferred from the config file has already be initialized.
        checkpoint_directory = f'{self.project_root}/checkpoints/{checkpoint}'
        
        # Load config
        config_path = os.path.join(checkpoint_directory, 'config.yaml')
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)
            
        database_path = os.path.join(checkpoint_directory, 'database.json')
        # Load data from file
        with open(database_path, 'r') as f:
            load_data = json.load(f)
        
        # Load basic state
        self._best_score_per_island = load_data["best_score_per_island"]
        self._last_reset_time = load_data["last_reset_time"]

        # Load best solutions per island
        self._best_solution_per_island = []
        for sol_dict in load_data["best_solution_per_island"]:
            if sol_dict is None:
                self._best_solution_per_island.append(None)
            else:
                # Convert dict back to Solution object
                solution = Solution(**sol_dict)
                self._best_solution_per_island.append(solution)

        # Clear existing islands and rebuild from loaded data
        self._islands = []
        for island_data in load_data["islands"]:
            # Create new island with current config
            island = Island(self.config, island_id=island_data["island_id"])
            island._num_programs = island_data["num_programs"]

            # Rebuild clusters for this island
            for features_key, cluster_data in island_data["clusters"].items():
                # Parse features key back to tuple or None
                if features_key == "None":
                    features = None
                else:
                    # Convert string like "(1, 2, 3)" back to tuple
                    features = eval(features_key)  # Safe because we saved it as str(tuple)

                # Create first solution to initialize cluster
                if not cluster_data["solutions"]:
                    continue  # Skip empty clusters

                first_sol_dict = cluster_data["solutions"][0]
                first_solution = Solution(**first_sol_dict)
                first_solution.island_id = island.island_id

                # Create cluster with first solution
                # we distinguish between first and latter solutions since
                # we need to create `Cluster` when adding the first solution
                if features is None:
                    # For None features, use random key as in Island.add()
                    features = random.getrandbits(32)
                    island._clusters[features] = Cluster(self.config, first_solution)
                else:
                    island._clusters[features] = Cluster(self.config, first_solution)

                # Set cluster score
                island._clusters[features]._score = cluster_data["score"]

                # Add remaining solutions to the cluster
                for i, sol_dict in enumerate(cluster_data["solutions"][1:], 1):
                    solution = Solution(**sol_dict)
                    solution.island_id = island.island_id
                    # Note: we add this way since have already restored cluster score
                    # alternatively, we could invoke Cluster.add() to rebuild score.
                    island._clusters[features]._solutions.append(solution)
                    island._clusters[features]._lengths.append(cluster_data["lengths"][i])

            self._islands.append(island)





class Island:
    """A sub-population of the programs database."""
    def __init__(self, config: dict, island_id=None) -> None:
        self.config = config
        self.island_id = island_id
        self.obj_type = self.config['experiment']['obj_type'].lower().strip()
        self.cluster_sampling_temperature_init = self.config['database']['cluster_sampling_temperature_init']  # temperature for the cluster sampling
        self.cluster_sampling_temperature_period = self.config['database']['cluster_sampling_temperature_period']  # period of linear decay of the cluster sampling temperature
        self._clusters: dict[Tuple[int, ...], Cluster] = {}
        self._num_programs: int = 0
        
    def add(self, solution: Solution) -> None:
        """Stores a solution on this island, in its appropriate cluster."""
        if solution.features is None:
            # If no features are provided, we always assume that the solution is a new cluster that contains only one solution
            # For easy of use, we use a random int as the cluster signature
            # Note: solution field `feature` is NOT changed, still None.
            self._clusters[random.getrandbits(32)] = Cluster(self.config, solution)
        elif solution.features not in self._clusters:
            # reduce the test scores to a single score for the program (hence the new cluster)
            self._clusters[solution.features] = Cluster(self.config, solution)
        else:
            # otherwise, invoke cluster.add() to add the program to the existing cluster
            self._clusters[solution.features].add(solution)
        self._num_programs += 1

    def sample(self, num_parents):
        """Sample from this island."""
        features_list = list(self._clusters.keys())  # each cluster has a signature; get all clusters' features_list
        cluster_scores = np.array([self._clusters[features]._score for features in features_list])
        cluster_scores = - cluster_scores if self.obj_type == 'min' else cluster_scores
        cluster_scores_normalized = (cluster_scores - min(cluster_scores)) / (max(cluster_scores) + 1e-6)
        # we normalize score here since the problems we test have very different scales
        # it's difficult to set appropriate sampling temperature if we don't normalize score
        # at the start of research, the differences between "good" and "bad" solutions scores are large
        # as study goes on, the differences between good solutions get smaller and smaller
        # TODO: you may want to use strategies to sample good solution more as study goes on?
        # although island reset may alleviate this
        # "elitist are sampled less and how to do?" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        
        if len(features_list) == 0:
            raise ValueError('No clusters found.')
        
        # Sample clusters
        # Convert scores to probabilities using softmax with temperature schedule.
        # Cf. Funsearch, paper, p9, Eqn (1):
        # When sampling a cluster, we favour those with better score values.
        # Note: temperature cool down linearly from init to 0 over the specified period.
        # TODO: there are many alternatives
        # "about temperature setting, first exploit or first explore? what's the pattern?" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        period = self.cluster_sampling_temperature_period
        # temperature: decrease from 1 to 0, then set to 1, so on so forth
        temperature = self.cluster_sampling_temperature_init * (1 - (self._num_programs % period) / period)
        # temperature: increase from 0 to 1, then decrease to 0, so on so forth
        # so, this scheme exploit more at the beginning
        #temperature = self.cluster_sampling_temperature_init * ((self._num_programs % period) / period)
        probabilities = _softmax(cluster_scores_normalized, temperature)
        probabilities += 1e-4  # to avoid zero probabilities
        probabilities /= np.sum(probabilities)  # re-normalize to sum to 1

        # choose `num_parents` many clusters according to the probabilities
        '''deprecated
        num_parents = min(len(self._clusters), num_parents)
        idx = np.random.choice(len(features_list), size=num_parents, p=probabilities)
        '''
        sample_size = min(len(features_list), num_parents)
        if sample_size < num_parents:
            print(f"\n>>>[Database] Warning: not enough clusters (only {sample_size}; required {num_parents} parents)!")
        idx = np.random.choice(len(features_list), size=sample_size, p=probabilities, replace=False)  # sample without replacement
        # if we sample with replacement, the same function may be selected; thus causing trouble!
        chosen_features_list = [features_list[i] for i in idx]
        parents = []  # Stores the samples
        for features in chosen_features_list:
            cluster = self._clusters[features]
            solution = cluster.sample()
            parents.append(solution)  # Invoke cluster.sample_program() to sample a program from the cluster

        # Handle the edge case: there are not enough clusters hence not enough parents; we sample with replacement
        # TODO: there could be a better way to handle this edge case; say manually adjust the features generation method in `eval.py`.
        # Here we implement a simpler solution
        # "when not enough clusters in an island, how to sample?" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        count = 0
        while len(parents) < num_parents:
            count += 1
            if count > 100:
                    print(f">>>[Database] Warning: too many attempts to sample a unique solution from the program database.")
                    break
            idx = np.random.choice(len(features_list))  # sample one feature randomly
            features = features_list[idx]
            cluster = self._clusters[features]
            solution = cluster.sample()
            if solution in parents:
                continue  # Skip if the solution is already in the parents
            parents.append(solution)
        
        # Sort solutions by their cluster scores.
        # So the best solution is more close to the end of the prompt.
        return sorted(parents, key=lambda x: x.score, reverse=True if self.obj_type == 'min' else False)
         




class Cluster:
    """
    A cluster of programs on the same island and with the same Signature.
    """

    def __init__(self, config: Dict, solution: Solution):
        self.config = config
        self._score = solution.score  # score of the cluster
        self._solutions: list[Solution] = [solution]  # list of functions in the cluster
        self._lengths: list[int] = [len(solution.code)]  # lengths of the code in the cluster
        
    @property
    def score(self) -> float:
        """Reduced score of the solution that this cluster represents."""
        return self._score
    
    def add(self, solution: Solution) -> None:
        """
        Adds solution to the cluster.
        If we use test scores to define signature, all programs in the same cluster have the same score. No need to update self._score.
        Note: If apply other ways to define signature (say the function features like length), then this function may be modified to update self._score.
        """
        self._solutions.append(solution)  # we will append the detailed metrics to prompt
        self._lengths.append(len(solution.code))  # we cared about function length since we prefer shorter programs
        # Update score
        # Here we changed the score to be the average score
        # TODO: there are alternative ways to define cluster score
        # "how to define score of cluster?" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        self._score = (self._score * (len(self._solutions) - 1) + solution.score) / len(self._solutions)
        
    def sample(self) -> Solution:
        """
        Samples a solution, giving higher probability to shorter programs.
        Cf. Funsearch, paper, p9:
        "When sampling a program within a cluster, we favour shorter programs."
        Note:
        Users can customize the sampling strategy here.
        """
        normalized_lengths = (np.array(self._lengths) - min(self._lengths)) / (max(self._lengths) + 1e-6)
        probabilities = _softmax(-normalized_lengths, temperature=1.0)  # remember to take negative of length before softmax
        chosen_idx = np.random.choice(range(len(self._solutions)), p=probabilities)  # sample one solution
        return self._solutions[chosen_idx]
    





if __name__ == '__main__':
    # Simple test to verify basic functionality
    print("Testing SolutionDatabase basic functionality...")

    # Create a mock config for testing
    test_config = {
        'experiment': {'obj_type': 'max'},
        'database': {
            'num_islands': 2,
            'reset_period_minutes': 3600,
            'cluster_sampling_temperature_init': 0.1,
            'cluster_sampling_temperature_period': 30000
        },
        'num_parents': 2
    }

    # Test _softmax
    print("\n=====1. Testing _softmax:=====")
    # logits have length 20, with values sampled from Uniform [0, 1] distribution
    # test temperatures: 0.1, 0.2, 0.5, 1.0
    np.random.seed(42)  # For reproducibility
    test_logits = np.random.uniform(0, 1, 20)
    test_logits = sorted(test_logits, reverse=True)
    test_logits = np.array(test_logits)
    temperatures = [0.1, 0.2, 0.5, 1.0]
    with np.printoptions(precision=2, suppress=True):
        print(f"Logits: {test_logits}")
        print("="* 50)
        for i, temp in enumerate(temperatures):
            probs = _softmax(test_logits, temperature=temp)
            tmp_str = '-'*50 if i != 0 else ""
            print(tmp_str)
            print(f"Temperature: {temp}")
            print(f"Probabilities: {probs}")
            print()

    # Test Cluster
    print("\n=====2. Testing Cluster:=====")
    test_solution = Solution(
        idea="Test idea",
        code="def test(): return 42",
        score=0.8,
        features=(1, 2, 3)
    )
    cluster = Cluster(test_config, test_solution)
    print(f"Cluster score: {cluster._score}")
    print(f"Number of solutions in cluster: {len(cluster._solutions)}")

    # Test Island
    print("\n=====3. Testing Island:=====")
    island = Island(test_config)
    island.add(test_solution)
    print(f"Island has {len(island._clusters)} cluster(s)")
    print(f"Island has {island._num_programs} program(s)")

    # Test SolutionDatabase and visualize method
    print("\n=====4. Testing SolutionDatabase.visualize():=====")
    db = SolutionDatabase()

    # Add some test solutions
    sol1 = Solution(
        idea="Test idea 1",
        code="def test1(): return 1",
        score=0.7,
        features=(1, 2, 3),
        island_id=0
    )

    sol2 = Solution(
        idea="Test idea 2",
        code="def test2(): return 2",
        score=0.9,
        features=(1, 2, 3),  # Same features as sol1 - should go to same cluster
        island_id=0
    )

    sol3 = Solution(
        idea="Test idea 3",
        code="def test3(): return 3",
        score=0.6,
        features=(4, 5, 6),  # Different features - should create new cluster
        island_id=0
    )

    sol4 = Solution(
        idea="Test idea 4",
        code="def test4(): return 4",
        score=0.8,
        features=(7, 8, 9),  # Different features - should create new cluster in island 1
        island_id=1
    )

    db.add([sol1, sol2, sol3, sol4])

    # Test visualization
    db.visualize()

    # Test save and load functionality
    print("\n=====5. Testing save() and load() methods:=====")

    # Save the database to a temporary file
    import tempfile
    import os

    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as tmp_file:
        temp_filepath = tmp_file.name

    try:
        # Save the database
        print(f"Saving database to: {temp_filepath}")
        db.save(temp_filepath)
        print("✓ Database saved successfully")

        # Check that file exists and has content
        file_size = os.path.getsize(temp_filepath)
        print(f"✓ Saved file size: {file_size} bytes")

        # Create a new database instance with same config
        print("\nCreating new database instance with same config...")
        db2 = SolutionDatabase()

        # Load the saved data
        print(f"Loading database from: {temp_filepath}")
        db2.load(temp_filepath)
        print("✓ Database loaded successfully")

        # Verify basic properties match
        print("\nVerifying loaded database matches original:")

        # Check number of islands
        assert len(db._islands) == len(db2._islands), f"Island count mismatch: {len(db._islands)} vs {len(db2._islands)}"
        print(f"✓ Island count matches: {len(db._islands)}")

        # Check total number of solutions
        orig_total = len(db)
        loaded_total = len(db2)
        assert orig_total == loaded_total, f"Total solutions mismatch: {orig_total} vs {loaded_total}"
        print(f"✓ Total solutions match: {orig_total}")

        # Check best scores per island
        for i in range(len(db._best_score_per_island)):
            orig_score = db._best_score_per_island[i]
            loaded_score = db2._best_score_per_island[i]
            assert abs(orig_score - loaded_score) < 1e-6, f"Best score mismatch for island {i}: {orig_score} vs {loaded_score}"
        print("✓ Best scores per island match")

        # Check island structures
        for i, (orig_island, loaded_island) in enumerate(zip(db._islands, db2._islands)):
            # Check number of clusters
            assert len(orig_island._clusters) == len(loaded_island._clusters), \
                f"Cluster count mismatch for island {i}: {len(orig_island._clusters)} vs {len(loaded_island._clusters)}"

            # Check number of programs
            assert orig_island._num_programs == loaded_island._num_programs, \
                f"Program count mismatch for island {i}: {orig_island._num_programs} vs {loaded_island._num_programs}"

            # Check cluster scores
            for features, orig_cluster in orig_island._clusters.items():
                # Find matching cluster in loaded island
                loaded_cluster = None
                for loaded_features, cluster in loaded_island._clusters.items():
                    if str(features) == str(loaded_features):
                        loaded_cluster = cluster
                        break

                assert loaded_cluster is not None, f"Cluster with features {features} not found in loaded island {i}"
                assert abs(orig_cluster._score - loaded_cluster._score) < 1e-6, \
                    f"Cluster score mismatch for features {features}: {orig_cluster._score} vs {loaded_cluster._score}"

                # Check number of solutions in cluster
                assert len(orig_cluster._solutions) == len(loaded_cluster._solutions), \
                    f"Solution count mismatch for cluster {features}: {len(orig_cluster._solutions)} vs {len(loaded_cluster._solutions)}"

        print("✓ All island structures match")

        # Test that we can sample from loaded database
        print("\nTesting sampling from loaded database...")
        samples = db2.sample(2)
        assert len(samples) == 2, f"Expected 2 samples, got {len(samples)}"
        print(f"✓ Successfully sampled {len(samples)} solutions from loaded database")

        # Test that best solution retrieval works
        best_solution = db2.get_best()
        assert best_solution is not None, "Best solution should not be None"
        print(f"✓ Best solution retrieved successfully with score: {best_solution.score}")

        print("\n✓ All save/load tests passed!")

    finally:
        # Clean up temporary file
        if os.path.exists(temp_filepath):
            os.unlink(temp_filepath)
            print(f"\nCleaned up temporary file: {temp_filepath}")

    print("\nBasic tests completed!")
