# src/oragent/utils.py
"""
# Utils for OR-Agent

Note: 
1. Commonly used datatypes (like `Solution`) should be defined here; private datatypes (like `Node`) can be defined in their own modules.
2. This `utils` module should NOT import other OR-agent modules to avoid circular imports.


## What the script contains:
Data type and data class definitions
 - Solution: solution type definition
 
LLM clients
 - LLMClient

Other utilities
 - init_json_list: initialize json list file
 - append_json_list: append a new item to a json list file
 - file_to_string: Read a file as string
 - extract_python_code: extract python code from string
 - wrap_python_code: wrap python code with fenced block
 - extract_diff_block: extract diff code from fenced block
 - extract_json: extract json dict or list from string
 - add_imports_to_code: Add imports to the code at the beginning of the code
 - is_valid: Check if the solution is valid
 - parents_to_str: Convert a list of solutions to a string
 - truncate: Truncate experiment output if it's too verbose
 - update_parameter: Update parameter values in the current solution code
 - update_code: Update code blocks by specifying code diff
 
Utils for ReEvo, EoH, AEL, FunSearch, kept for compatibility
 - parent_selection: Select parents using rank-based probabilistic selection
 - rank_select: Rank-based selection, select individuals with probability proportional to their rank
 - random_select: Random selection, select individuals with equal probability
 - response_to_individual: Convert response to individual
 - responses_to_population: Convert responses to population
 - individual_to_str: Convert an individual to a string
"""
import os 
import sys
import json
import time
import yaml
import numpy as np
from dataclasses import dataclass, field
from typing import List, Tuple, Optional, Dict, Union, Any
from openai import OpenAI
import concurrent
import random
from pathlib import Path
import re
from dotenv import load_dotenv


load_dotenv()


# ===== Data type and data class definitions =====
@dataclass
class Solution:
    _next_id = 0  # Class-level counter
    """
    `Solution` dataclass fields:
    (IDs)
    - `id` (int): Auto-incremented unique ID for each solution.
    - `lead_agent_id` (int): The ID of the lead agent who generated this solution. Default: `None`.
    - `research_round`(int): The research round number when this solution is generated by the LeadAgent. Default: `None`.
    - `solution_count` (int): The count of the solution in the current research round.  Default: `None`.
    (Body)
    - `idea` (str): The conceptual approach of the solution. Generated by the IdeaAgent. Default: `None`.
    - `code` (str): The code implementation of the idea. Generated by the CodeAgent. Default: `None`.
    - `code_filepath` (str): The path to the code file: f"{output_dir}/{id_str}_solution.py". Generated by the Evaluator. Default: `None`. 
    - `output` (str): The stdout of solution execution. Generated by the Evaluator. Default: `None`.
    - `output_filepath` (str): The path to the stdout file: f"{output_dir}/{id_str}_stdout.txt". Generated by the Evaluator. Default: `None`.
    - `metrics` (Dict): Performance metrics of the solution. Generated by the Evaluator. Default: `{}`.
    - `features` (Tuple[int, ...]): Feature vector of the solution, used by the MAP-Elites-based solution database for indexing. Generated by the Evaluator. Default: `None`.
    - `score` (float): Overall score of the solution. Generated by the Evaluator. Default: `None`.
    - `summary` (str): Final verdict on the solution's quality along with insights for future iterations. Generated by the ExperimentAgent. Default: `None`.
    - `island_id` (int): The ID of the island where the solution was found in solution database. Used by OR-Agent and FunSearch. Default: `None`.
    (The following fields are used to store temporary data generated during experiments)
    - `intermediate_codes` (List[str]): Code generated during iterative experiments. Generated by ExperimentAgent. Default: `[]`.
    - `intermediate_outputs` (List[str]): Results collected during iterative experiments. Generated by the Evaluator. Default: `[]`.
    - `intermediate_metrics` (List[Dict]): Performance metrics collected during iterative experiments. Generated by the Evaluator. Default: `[]`.
    - `intermediate_features` (List[Tuple[int, ...]]): Feature vectors collected during iterative experiments. Generated by the Evaluator. Default: `[]`.
    - `intermediate_scores` (List[float]): Scores collected during iterative experiments. Generated by the Evaluator. Default: `[]`.
    - `intermediate_actions` (List[str]): Actions during experiments. Generated by the ExperimentAgent. Default: `[]`.
    (The following ID fields are used by ReEvo, EoH, AEL, and FunSearch; kept for compatibility)
    - `iteration` (int): The iteration number when this solution was found. Default: `None`.
    - `response_id` (int): The index of the response from the LLM. Default: `None`.
    
    Usage:
    Convert Solution instance to Dict: `sol_dict = dataclasses.asdict(sol)`
    Convert Dict to Solution instance: `sol = Solution(**sol_dict)`
    """
    # PS: variables defined inside the @dataclass field list (i.e., annotated with a type) become instance attributes.
    # Note: don NOT use [], {} for list or dict initialization; dangerous - objects will share the same instance! Use factory method
    id: int = None  # Auto-incrementing unique ID
    lead_agent_id: int = None  # ID of lead agent who generated the solution
    research_round: int = None  # research round when the solution is generated
    solution_count: int = None  # solution count when the solution is generated
    idea: Optional[str] = None
    code: Optional[str] = None
    code_filepath: Optional[str] = None
    output: Optional[str] = None
    output_filepath: Optional[str] = None
    metrics: Dict = field(default_factory=dict)  # Don't use {}
    features: Optional[Tuple[int, ...]] = None
    score: Optional[float] = None
    summary: Optional[str] = None
    island_id: Optional[int] = None
    intermediate_codes: List[str] = field(default_factory=list)
    intermediate_outputs: List[str] = field(default_factory=list)
    intermediate_metrics: List[Dict] = field(default_factory=list)
    intermediate_features: List[Tuple[int, ...]] = field(default_factory=list)
    intermediate_scores: List[float] = field(default_factory=list)
    intermediate_actions: List[str] = field(default_factory=list)
    # (The following fields are used by ReEvo, EoH, AEL, and FunSearch; kept for compatibility)
    iteration: Optional[int] = None
    response_id: Optional[int] = None
    
    def __post_init__(self):
        """Assign auto-incrementing ID if not provided."""
        if self.id is None:
            self.id = Solution._next_id
            Solution._next_id += 1

    def __str__(self) -> str:
        """Return a human-readable string representation of the Solution.
        PS: Intermediate experiment results are NOT included. Only include the body.
        
        **Example output:**
Idea: Use dynamic programming...
Code: def solve(n):...
Features: (10, 20, 5)
Metrics: {'accuracy': 0.92, 'speed': 1.23}
Score: 0.85
Summary: Good solution with high accuracy...
"""
        solution_str = f"""
**ID**
{self.id}

**Idea**: 
{self.idea}

**Code**:
```python
{self.code}
```

**Metrics**:
{self.metrics}

**Feature**
{self.features}

**Score**:
{self.score}

**Summary**:
{self.summary}
"""
        return solution_str.strip()


    def id_str(self, algorithm='oragent') -> str:
        """Get a string for the solution identity.
        PS: fields like iteration, response_id are added for better inspection.
        TODO: Revise it to display only `id` if you prefer more concise naming.
        # "customize visualization techniques" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        """
        if algorithm == "oragent":
            return f"lead{self.lead_agent_id}_round{self.research_round}_count{self.solution_count}_id{self.id}"
        else:
            return f"iter{self.iteration}_response{self.response_id}"
        
    def performance_str(self) -> str:
        """Return a string summarizing the solution's performance."""
        performance_str = f"""
**Metrics**:
{self.metrics}

**Score**:
{self.score}
"""
        return performance_str.strip()
    
    def performance_summary_str(self) -> str:
        """Return a string summarizing the solution's performance and summary."""
        performance_summary_str = f"""
**Metrics**:
{self.metrics}

**Score**:
{self.score}

**Summary**:
{self.summary}
"""
        return performance_summary_str.strip()
    
    def idea_performance_summary_str(self) -> str:
        """Return a string summarizing the solution's idea, performance, and summary."""
        idea_performance_summary_str = f"""
**Idea**:
{self.idea}

**Metrics**:
{self.metrics}

**Score**:
{self.score}

**Summary**:
{self.summary}
"""
        return idea_performance_summary_str.strip()
    
    def experiment_history(self, num_experiments=None) -> str:
        """
        Generate experiment history string by concatenating intermediate experiment results and reflections.
        
        Args:
            num_experiments (int): Number of experiments to include; default: None (includes all).
                If the allowed number of experiments is large, we recommend set `num_experiments` to avoid context growing too large for experiment agent.
        
        Returns:
            experiment_history_str (str): Formatted experiment history string.
            
        Example:
----------------------------------------
Experiment #1:
----------------------------------------
**Stdout**:
Test case 1 passed with score 0.8

**Metrics**:
{'accuracy': 0.8, 'speed': 2.0}

**Features**:
(8, 15, 3)

**Score**: 0.8

**Reflections and actions**:
Increased timeout limit

----------------------------------------
Experiment #2:
----------------------------------------
...
        """
        # Limit to num_experiments if specified
        # solution intermediate outputs and metrics length = actions length + 1
        # since the last evaluation remains to be reflected
        # we use len(self.intermediate_actions) to generate experiment history
        num_experiments = num_experiments or len(self.intermediate_actions)
            
        # Experiment tracking - print alternately
        # concat results of last `num_experiments` experiment results.
        experiment_history_str = ''
        start_index = max(0, len(self.intermediate_actions) - num_experiments)
        for i in range(start_index, len(self.intermediate_actions)):
            tmp_str = f"\n{'-'*40}\nExperiment #{i + 1}:\n{'-'*40}\n"
            tmp_str += f"**Stdout**:\n{self.intermediate_outputs[i]}\n\n"
            tmp_str += f"**Metrics**:\n{self.intermediate_metrics[i]}\n\n"
            tmp_str += f"**Features**:\n{self.intermediate_features[i]}\n\n"
            tmp_str += f"**Score**: {self.intermediate_scores[i]}\n\n"
            tmp_str += f"**Reflections and actions**:\n{self.intermediate_actions[i]}\n"
            experiment_history_str += tmp_str
        return experiment_history_str.strip()





# ===== LLM client =====
class LLMClient:
    def __init__(self, config=None, llm_provider=None, model_name=None, **kwargs):
        """
        Initialize the LLM client.
        If `llm_provider` is not in ['openai', 'qwen', 'deepseek'], you should set `llm_provider` to be None and 
        provide the following parameters in `kwargs`: 
        - `api_key`
        - `base_url`
        
        Args:
            llm_provider (str): The LLM provider name
            model_name (str): The model name to use
            **kwargs: Additional arguments passed to the OpenAI client
        """
        self.package_dir = Path(__file__).parent
        self.project_root = Path.cwd()
        if config:
            self.config = config
        else:
            # Load built-in config if config is not provided
            with open(f'{self.package_dir}/config.yaml', 'r') as f:
                self.config = yaml.safe_load(f)
        
        # -----LLM client settings-----
        self.max_tries = self.config["model"]["max_retries"]
        # If LLM is not specified, use default LLM settings from config file
        self.llm_provider = llm_provider or self.config["model"]["llm_provider"]
        self.model_name = model_name or self.config["model"]["model_name"]
        
        # Create client
        if "openai" in self.llm_provider.lower():
            self.client = OpenAI(
                api_key=os.getenv("OPENAI_API_KEY"),
                base_url="https://api.openai.com/v1",
                **kwargs
            )
        elif "qwen" in self.llm_provider.lower():
            self.client = OpenAI(
                api_key=os.getenv("DASHSCOPE_API_KEY"),
                base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
                **kwargs
            )
        elif "deepseek" in self.llm_provider.lower():
            self.client = OpenAI(
                api_key=os.getenv("DEEPSEEK_API_KEY"),
                base_url="https://api.deepseek.com",
                **kwargs
            )
        else:
            try:
                self.client = OpenAI(
                    **kwargs  # include `api_key` and `base_url` in `kwargs` in this case
                )
            except:
                raise ValueError(f"Invalid model config: {kwargs}")


    def chat(self, messages: list[dict], **kwargs) -> str:
        """
        Generate one response using OpenAI Chat Completions API.
        
        Args:
            messages (list[dict]): One round of messages
            **kwargs: Additional arguments passed to the chat completions API
            
        Returns:
            str: LLM response string
        """
        choices = None
        for attempt in range(self.max_tries):
            try:
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=messages,
                    **kwargs
                )
                choices = response.choices
                if not choices:
                    print("\n>>>[LLMClient] None response generated")
                else:
                    # check to make sure that choices is not none, then you can break! 
                    # otherwise, sometimes it returns None, and you will regard this as a successful generation
                    break
            except Exception as e:
                sleep_time = random.randint(3, 60)
                print(f"\n>>>[LLMClient] Attempt {attempt + 1} failed with error: {e}; sleep for {sleep_time} seconds")
                time.sleep(sleep_time)
                # Note: add random sleep time to avoid too frequent LLM call
                # TODO: this is a simple trick; could be made better
                # "devise technique to avoid LLM calls flooding" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        
        if choices is None:
            print("\n>>>[LLMClient] All retry attempts failed!")
            raise RuntimeError("\n>>>[LLMClient] All retry attempts failed")
        
        return choices[0].message.content

    def multi_chat(self, messages_list: list[list[dict]], n: int = 1, **kwargs) -> list[str]:
        """
        This function serves two goals:
        1) Process multiple conversations concurrently - Takes a list of message rounds 
           and generates one response for each message round in parallel using ThreadPoolExecutor.
           In this case, `n` must be one;
        2) Take single message round, then generate multiple responses for this conversation - 
           The `n` parameter controls how many responses to generate.

        Args:
            messages_list (list[list[dict]]): List of message rounds;
                An example of messages_list:
                messages_list = [
                    [
                        {"role": "system", "content": "You are a helpful assistant."},
                        {"role": "user", "content": "Hello!"},
                    ],
                    [
                        {"role": "system", "content": "You are a knowledgeable guide."},
                        {"role": "user", "content": "How are you?"},
                    ],
                    [
                        {"role": "system", "content": "You are a witty comedian."},
                        {"role": "user", "content": "Tell me a joke."},
                    ]
                ]
                messages_list[i] is a list of messages (a multi-round chat)
            n (int): Number of responses to generate
            **kwargs: Additional arguments passed to the chat completions API
        
        Returns:
            list[str]: A list of response strings
        """
        assert isinstance(messages_list, list), "messages_list should be a list."
        if not isinstance(messages_list[0], list):
            messages_list = [messages_list]

        if len(messages_list) > 1:
            assert n == 1, "When processing multiple conversations, n must be 1"
        elif n > 1:
            # Note messages_list has to has length == 1 before this step; 
            # and we need to generate n completions for this message; 
            # so we expand the messages_list to n copies; and later we will use `concurrent` to process them in parallel
            messages_list = messages_list * n

        # Async LLM call
        with concurrent.futures.ThreadPoolExecutor() as executor:
            args = [dict(messages=messages, **kwargs) for messages in messages_list]
            contents = list(executor.map(lambda p: self.chat(**p), args))
        
        return contents





# ===== Other utilities =====
def init_json_list(filepath: str):
    """If the file exists, clear the filepath to be a empty json list; if not, create a new empty json list file."""
    with open(filepath, "w") as fp:
        results = []
        json.dump(results, fp, indent=4, default=str)


def append_json_list(filepath: str, item: Any):
    """Update a JSON list file by appending a new item.

    Args:
        filepath: Path to the JSON file
        item: item to add to the JSON file
    """
    if os.path.exists(filepath):
        with open(filepath, "r") as fp:
            results = json.load(fp)
    else:
        results = []  # Note: if the file does not exist, we create a new one
    results.append(item)
    
    with open(filepath, "w") as fp:
        json.dump(results, fp, indent=4, default=str)
    

def file_to_string(filename) -> str:
    """Read a file as string.

    Args:
        filename: Path to the file to read

    Returns:
        String content of the file

    Raises:
        FileNotFoundError: If the file does not exist
        IsADirectoryError: If the path is a directory
    """
    if not os.path.exists(filename):
        raise FileNotFoundError(f"[Utils] File not found: {filename}")

    if os.path.isdir(filename):
        raise IsADirectoryError(f"[Utils] Path is a directory, not a file: {filename}")

    with open(filename, 'r') as file:
        return file.read()


def extract_thinking(text: str) -> Optional[str]:
    """
    Extract content from <thinking> tags in a string.
    
    Args:
        text: String that may contain <thinking>...</thinking> tags
        
    Returns:
        The content inside the thinking tags (stripped of leading/trailing whitespace),
        or None if no thinking tags are found
        
    Examples:
        >>> extract_thinking("<thinking>Analysis here</thinking>")
        'Analysis here'
        >>> extract_thinking("No tags here")
        None
        >>> extract_thinking("<thinking>\\nMulti-line\\nthinking\\n</thinking>")
        'Multi-line\\nthinking'
    """
    pattern = r'<thinking>(.*?)</thinking>'
    match = re.search(pattern, text, re.DOTALL)
    
    if match:
        return match.group(1).strip()
    return None


def extract_python_code(text: str) -> Optional[str]:
    """
    Extract Python code from markdown code blocks.
    
    Args:
        text: String containing markdown with ```python code blocks
        
    Returns:
        The extracted Python code, or None if no code block found
    """
    if not text:
        return None
    
    pattern = r'```python\s*(.*?)```'
    match = re.search(pattern, text, re.DOTALL)
    
    if match:
        code = match.group(1).strip()
        return code
    
    print("\n>>>[Utils] No python code block identified.")
    return None

def wrap_python_code(code: str) -> str:
    """
    Wrap Python code in ```python ... ``` fences.
    
    Args:
        code: Python code to wrap
        
    Returns:
        The wrapped code
    """
    return f"```python\n{code}\n```"


def extract_diff_block(text: str) -> Optional[str]:
    """
    Extract code diff ONLY from ```diff ... ``` fenced blocks.

    Rules:
    - Must be fenced with ```diff
    - Ignore other languages (python/json/etc.)
    - Ignore unfenced text
    - Return raw diff content without fences
    """
    if not text:
        return None

    match = re.search(
        r"```diff\s*\n(.*?)```",
        text,
        flags=re.DOTALL | re.IGNORECASE
    )

    if not match:
        print("\n>>>[Utils] No diff block identified.")
        return None

    return match.group(1).rstrip()


def extract_json(response: str) -> Union[List[Any], Dict[str, Any], None]:
    """
    Extract the first valid JSON object or array from a text response.
    The function may return either a JSON object or a JSON array

    This function is designed for LLM outputs, which often:
        - wrap JSON in ```json ... ``` fences
        - include explanatory text before / after the JSON
        - include invalid raw newlines inside JSON string values

    Strategy:
        1. Prefer extracting content inside a fenced code block.
        2. Otherwise, locate the first balanced {...} or [...] region.
        3. Parse with json.loads().
        4. If parsing fails, repair common LLM formatting errors and retry.

    Returns:
        Parsed JSON (dict or list) if successful, otherwise None.
    """

    if not response:
        return None

    # ------------------------------------------------------------
    # STEP 1: Strictly match ```json ... ``` fences only
    # ------------------------------------------------------------
    # handle default LLM output: JSON in ```json ... ``` fence
    match = re.search(
        r"```json\s*(.*?)\s*```",
        response,
        flags=re.DOTALL | re.IGNORECASE
    )

    # ------------------------------------------------------------
    # STEP 2: Try to decode directly
    # ------------------------------------------------------------    
    if not match:
        # for the case ```json ... ``` fence is not found
        # try to load directly
        try:
            return json.loads(response)
        except json.JSONDecodeError:
            print(f"\n>>>[Utils] JSON parsing failed: \n{response}")
        return None
    
    candidate = match.group(1).strip()
    # ------------------------------------------------------------
    # STEP 3: Attempt strict JSON parsing
    # ------------------------------------------------------------
    try:
        return json.loads(candidate)

    except json.JSONDecodeError:
        # ------------------------------------------------------------
        # STEP 4: Repair common LLM JSON errors and retry
        # ------------------------------------------------------------
        # Common issues:
        # - LLMs frequently emit raw newline characters inside JSON string values, which is illegal in JSON.
        # - Single quotes are NOT valid like {'hello': 'world'}
        # - trailing commas like {  "projects": ["A", "B",]}
        #
        # In this function, we only repair the first issue manually
        # TODO: there are other ways to handle those issues, like using LLM call for remedy
        # "remedy LLM response format error" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
        # 
        # Examples:
        # s = '{"hello": "world"}'        # VALID
        # s = '{"hello": "world"\n}'      # VALID; \n is outside the string literal
        # s = '{"hello": "world\n"}'      # INVALID representation of \n; 
        #                                   The \n here is a literal newline character, not the two-character escape sequence \\n.
        #                                   JSON does not allow raw control characters (U+0000–U+001F) inside strings.
        #                                   json.loads('{"hello": "world\n"}') reports JSONDecodeError
        #                                   You need the backslash to be part of the JSON text itself.
        # s = "{'hello': 'world'}"        # INVALID using of single quotes; Single quotes are not permitted anywhere in JSON syntax
        #
        # This repair pass escapes:
        #   \n → \\n
        #   \r → \\r
        #   \t → \\t
        #
        # BUT ONLY when inside string literals.
        # ------------------------------------------------------------
        def escape_controls_in_strings(s: str) -> str:
            out = []
            in_string = False
            escape = False

            for c in s:  # Walks the JSON text one character at a time
                if in_string:
                    # Escapes illegal control characters only when they occur inside string literals.
                    if escape:
                        out.append(c)
                        escape = False
                    elif c == "\\":
                        out.append(c)
                        escape = True
                    elif c == '"':
                        out.append(c)
                        in_string = False
                    elif c == "\n":  # Invalid character inside string literal; replace with \\n
                        out.append("\\n")
                    elif c == "\r":
                        out.append("\\r")
                    elif c == "\t":
                        out.append("\\t")
                    else:
                        out.append(c)
                else:  # If outside of string literal, \n is valid character
                    out.append(c)
                    if c == '"':
                        in_string = True

            return "".join(out)

        # We deliberately do NOT auto-convert single quotes
        # The function is explicitly a JSON extractor, not a “parse whatever” extractor.
        # It is ambiguous and unsafe
        
        # Apply repair and retry parsing
        fixed = escape_controls_in_strings(candidate)

        try:
            return json.loads(fixed)
        except Exception:
            # Still invalid — give up
            print(f"\n>>>[Utils] No JSON block identified: {fixed}")
            return None


def add_imports_to_code(code: str) -> str:
    """ 
    Add imports to the code at the beginning of the code.
    This simple trick can settle a common issue of LLM generated code - forgetting to import relevant libs.
    TODO: you may want to customize this according to your problems
    """
    additional_imports = [
        "import os",
        "import sys",
        "import time",
        "import random",
        "import math",
        "import json",
        "import numpy as np",
        "import pandas as pd",
        "import scipy",
        "import traci",
        "import torch",
    ]
    return "\n".join(additional_imports) + "\n\n" + code


def is_valid(solution: Solution)-> bool:
    """
    Check if the solution is valid.
    Here we check three important fields: idea, code, and score.
    """
    return (solution.idea is not None) and (solution.code is not None) and (solution.score is not None)


def parents_to_str(parent_solutions: Union['Solution']=None) -> str:
    """Convert a list of solutions to a string.

    Example:
----------------------------------------
Parent #1:
----------------------------------------
**Idea**: 
Parent idea 1

**Code**:
```python
def parent1(): pass
```

**Metrics**:
{}

**Feature**
None

**Score**:
0.7

**Summary**:
None

----------------------------------------
Parent #2:
----------------------------------------
...
    """
    # Error handling
    if not parent_solutions:
        print("\n>>>[Utils] Warning: no parent solutions provided!")
        return None
    
    if parent_solutions and not isinstance(parent_solutions, list):
        parent_solutions = [parent_solutions]
    
    parent_solutions_str = ""
    if parent_solutions:
        for i, parent in enumerate(parent_solutions):
            parent_solutions_str = parent_solutions_str + f"\n{'-'*40}\nParent #{i + 1}:\n{'-'*40}\n" + str(parent) + '\n'
    return parent_solutions_str.strip()


def truncate(raw_output: str, max_lines=100) -> str:
    """
    Truncate experiment output if it's too verbose.
    
    Args:
        raw_output (str): experiment output
        max_lines (int): max number of lines to keep; default: 100
        
    Returns:
        truncated (str): truncated output
    """
    raw_output = raw_output.strip()
    lines = raw_output.splitlines()
    total_lines = len(lines)

    if total_lines <= max_lines:
        return raw_output

    # Keep only the first max_lines lines
    truncated = "\n".join(lines[:max_lines])
    # Add annotation so that LLM will know the result is too verbose; this is important!
    truncated += f"\n...\n[Output truncated: {total_lines} total lines, showing first {max_lines} lines]"
    
    # TODO: this represents a simple logic to shorten verbose environment output
    # there are alternatives; like you can extract important info, invoke LLM to compress to provide a summary, etc.
    # "how to manage and compress context?" - This requires further exploration, analysis, and validation, and is marked with a TODO flag
    return truncated


def update_parameter(curr_code: str, parameter_definitions: str):
    """
    Update parameter values in the current solution code.
    Parses parameter definitions and updates their values in the solution's code.
    If a parameter is not found in the current code, the definition is silently
    ignored to ensure robustness.
    
    Args:
        curr_code (str): The current code string of a solution.
        parameter_definitions (str): Parameter definitions to update, with each
            definition on a separate line (e.g., "a = 1.2\nb = 0.5").
    
    Returns:
        str: The updated code with modified parameter values.
    
    Example:
        If curr_code contains "a = 1.0" and parameter_definitions is "a = 1.2",
        the result will have "a = 1.2" in place of "a = 1.0".
    """
    # Split parameter definitions into individual lines
    definitions = parameter_definitions.strip().split('\n')
    
    for definition in definitions:
        definition = definition.strip()
        if not definition or '=' not in definition:
            continue
        
        # Parse parameter name and new value
        try:
            param_name, new_value = definition.split('=', 1)
            param_name = param_name.strip()
            new_value = new_value.strip()
        except ValueError:
            continue
        
        # Pattern to match parameter assignment
        # Matches: param_name = <any_value> (with optional whitespace)
        pattern = rf'^(\s*){re.escape(param_name)}\s*=\s*(.+?)(\s*#.*)?$'
        
        # Replace parameter value line by line
        lines = curr_code.split('\n')
        updated = False
        for i, line in enumerate(lines):
            match = re.match(pattern, line)
            if match:
                indent = match.group(1)
                comment = match.group(3) if match.group(3) else ''
                lines[i] = f'{indent}{param_name} = {new_value}{comment}'
                updated = True
                break  # Only replace first occurrence
        
        if updated:
            curr_code = '\n'.join(lines)
    
    return curr_code


def update_code(curr_code: str, code_diff: str):
    """
    Update code blocks in the current solution code.

    Args:
        curr_code (str): The current code string of a solution.
        code_diff (str): code modifications in conflict markers style, example:
<<<<<<< SEARCH
...
=======
...
>>>>>>> REPLACE
<<<<<<< SEARCH
...
=======
...
>>>>>>> REPLACE

    Returns:
        str: The updated code.
    """
    # Split the code_diff into individual conflict blocks
    lines = code_diff.split('\n')
    result = curr_code
    i = 0

    while i < len(lines):
        line = lines[i]
        # Look for conflict marker start
        if line.strip() == '<<<<<<< SEARCH':
            search_start = i
            # Find the ======= marker
            while i < len(lines) and lines[i].strip() != '=======':
                i += 1
            if i >= len(lines):
                break  # Malformed diff
            search_end = i
            i += 1  # Skip =======

            # Find the >>>>>>> REPLACE marker
            replace_start = i
            while i < len(lines) and lines[i].strip() != '>>>>>>> REPLACE':
                i += 1
            if i >= len(lines):
                break  # Malformed diff
            replace_end = i
            i += 1  # Skip >>>>>>> REPLACE

            # Extract search and replace blocks
            search_block = '\n'.join(lines[search_start + 1:search_end])
            replace_block = '\n'.join(lines[replace_start:replace_end])

            # Apply the replacement - replace only the first occurrence
            if search_block in result:
                # Find the position of the first occurrence
                pos = result.find(search_block)
                if pos != -1:
                    # Replace only at this position
                    result = result[:pos] + replace_block + result[pos + len(search_block):]
            else:
                # If exact match not found, try to find a similar block
                # by removing trailing whitespace from each line
                search_lines = [l.rstrip() for l in search_block.split('\n')]
                result_lines = result.split('\n')

                # Try to find the block in the result (preserving original indentation)
                for j in range(len(result_lines) - len(search_lines) + 1):
                    # Compare with trailing whitespace removed
                    if [l.rstrip() for l in result_lines[j:j + len(search_lines)]] == search_lines:
                        # Found a match, replace it
                        before = '\n'.join(result_lines[:j])
                        after = '\n'.join(result_lines[j + len(search_lines):])
                        result = before + '\n' + replace_block + '\n' + after
                        break
        else:
            i += 1

    return result





# =====Utils for ReEvo, EoH, AEL, FunSearch=====
# Kept for compatibility
def parent_selection(population: list[Solution], 
                     obj_type: str, 
                     m=2, 
                     denominator_expansion=False
                     ) -> list[Solution]:
    """ 
    Select parents using rank-based probabilistic selection.
    Note: very similar to rank_select; return different number of parents
    
    Args:
        pop (list): Population of individuals; shape: (P, n_decap); already sorted according to the rewards in ascending order.
        obj_type (str): Objective type; either "min" or "max".
        m (int): Number of parents to select.
        denominator_expansion (bool): Whether to expand the denominator of the rank probability.
        
    Returns:
        parents (list): Parent individuals; shape: (m, n_decap).
    """
    # sort population based on obj
    # so we can use rank-based probabilistic selection
    if obj_type == "min":
        population.sort(key=lambda x: x.score)
    else:
        population.sort(key=lambda x: x.score, reverse=True)
    pop_size = len(population)
    
    # Compute rank probabilities
    if denominator_expansion:
        rank_probs = [1 / (i + 1 + pop_size) for i in range(pop_size)]
        # pop_size is added to the denominator;
        # This is in accordance with the EoH paper (page 5, right column, paragraph 4);
        # This practice is different with the rank_selection in ael.py.
    else:
        rank_probs = [1 / (i + 1) for i in range(pop_size)]

    rank_probs = np.array(rank_probs) / np.sum(rank_probs)
    #ranks = [i for i in range(len(pop))]
    #probs = [1 / (rank + 1 + len(pop)) for rank in ranks]
    #parents = random.choices(population, weights=rank_probs, k=m)
    parents = np.random.choice(population, size=m, replace=False, p=rank_probs)
    
    return parents   


def rank_select(population: list[Solution], 
                obj_type, 
                pop_size, 
                denominator_expansion=False
                ) -> list[Solution]:
    """
    Rank-based selection, select individuals with probability proportional to their rank.
    Sample from the population, with probability proportional to their rank.
    
    Args:
        population (list[dict]): Population
        obj_type (str): Objective type
        pop_size (int): Population size
        denominator_expansion (bool): Whether to expand the denominator of the rank probability.
        
    Returns:
        list[dict]: Selected population; size: 2 * pop_size
    """
    population = [ind for ind in population if ind.score]
    selected_population = []
    if len(population) < 2:
        return None
    
    # Sort population by objective value
    if obj_type == "min":
        population.sort(key=lambda x: x.score)  # in-place sort
    else:
        population.sort(key=lambda x: x.score, reverse=True)
    
    # Compute rank probabilities
    # Note: How to select is not detailed in the ReEvo paper.
    # This implementation is from the ReEvo github repo.
    # It's a bit different from the parent selection method in the succeeded paper by the same author - len(pop) is added to the denominator there; see eoh.py.
    if denominator_expansion:
        rank_probs = [1 / (i + 1 + len(population)) for i in range(len(population))]
    else:
        rank_probs = [1 / (i + 1) for i in range(len(population))]
    rank_probs = np.array(rank_probs) / np.sum(rank_probs)
    # select pair of parents; self.cfg.pop_size pairs in total
    # parent should be different; hence replace=False
    # different parents may overlap
    for _ in range(pop_size):
        parents = np.random.choice(population, size=2, replace=False, p=rank_probs)
        selected_population.extend(parents)
    assert len(selected_population) == 2 * pop_size
    
    # Alternative rank-based selection in ReEvo
    """
    ranks = [i for i in range(len(population))]
    probs = [1 / (rank + 1 + len(population)) for rank in ranks]  # Note: how prob is calculated; EoH and AEL may use different formula
    # Normalize probabilities
    probs = [prob / sum(probs) for prob in probs]
    selected_population = []
    trial = 0
    # select pair of parents; self.cfg.pop_size pairs in total
    # parent should be different; hence replace=False
    # different parents may overlap
    while len(selected_population) < 2 * pop_size:
        trial += 1
        parents = np.random.choice(population, size=2, replace=False, p=probs)  # select two parents at a time; so that they will be different
        if parents[0].score != parents[1].score:
            selected_population.extend(parents)  # different parents could overlap
        if trial > 1000:
            return None
    return selected_population
    """
    
    return selected_population


def random_select(population: list[Solution], 
                  pop_size
                  ) -> list[dict]:
    """
    Random selection, select individuals with equal probability.
    Sample from the population with uniform distribution.
    
    Args:
        population (list[dict]): Population
        pop_size (int): Population size
        
    Returns:
        list[dict]: Selected population; size: 2 * pop_size
    """
    selected_population = []
    # Eliminate invalid individuals
    population = [ind for ind in population if ind.score]
    if len(population) < 2:
        return None
    
    attempt = 0
    while len(selected_population) < 2 * pop_size:  
        attempt += 1
        # 2 * self.cfg.pop_size is the number of parents
        parents = np.random.choice(population, size=2, replace=False)  # select two parents at a time
        # If two parents have the same objective value, consider them as identical; otherwise, add them to the selected population
        if parents[0].score != parents[1].score:
            selected_population.extend(parents)
            
        if attempt > 1000:
            print(f"\n>>>[Utils] Random selection failed after 1000 attempts; len(population)={len(population)}; pop_size={pop_size}; selected_population size={len(selected_population)}")
            raise RuntimeError(">>>[Utils] Random selection failed after 1000 attempts")
    
    return selected_population


def response_to_individual(response: str, 
                           iteration: int, 
                           response_id: int, 
                           output_dir: str
                           ) -> dict:
    """
    Convert response to individual.

    Args:
        response (str): Response from LLM
        response_id (int): Response ID
        output_dir (str): Output directory

    Returns:
        dict: Individual
    """
    # Write response to file
    # Here the LLM response ```python...```code is written to the individual's file
    # Use f"{self.output_dir}/{solution.id_str(self.algorithm)}.txt" format
    code_filepath = f"{output_dir}/details/iter{iteration}_response{response_id}.txt"

    with open(code_filepath, 'w') as file:
        file.writelines(response + '\n')

    # Extract code from LLM response
    code = extract_python_code(response)

    # Create stdout file path
    output_filepath = f"{output_dir}/details/iter{iteration}_response{response_id}_stdout.txt"

    # Create individual
    individual = Solution(iteration=iteration,
                        response_id=response_id,
                        code=code,
                        code_filepath=code_filepath,
                        output_filepath=output_filepath,
                        )
    return individual


def responses_to_population(responses: list[str], 
                            iteration: int, 
                            output_dir: str
                            ) -> list[Solution]:
    """
    Convert responses to population.
    Invoke `response_to_individual()` for each response.
    
    Args:
        responses (list[str]): Responses from LLM
        iteration (int): Iteration number
        output_dir (str): Output directory
        
    Returns:
        list[dict]: Population; list of individuals
    """
    population = []
    for response_id, response in enumerate(responses):
        individual = response_to_individual(response=response, 
                                            iteration=iteration, 
                                            response_id=response_id, 
                                            output_dir=output_dir)
        population.append(individual)
    return population


def individual_to_str(individual: Solution) -> str:
    """
    Convert an individual to a string.
   
    Args:
        individual (dict): Individual
        
    Returns:
        str: Individual as a string
    """
    # if ind has obj
    if individual.score:
        score_str =  str(individual.score)
    else:
        score_str = "(not available)"

    ans = f"""
**Code**:
```python
{individual.code}
```

**Objective**: {score_str}
"""
    return ans.strip()







if __name__ == "__main__":
    # Test utility functions
    print("=== Testing utility functions ===\n")

    # Test Solution tostring method
    print("1.1. Testing Solution __str__ method:")
    test_solution = Solution(
        idea="Use dynamic programming to solve the knapsack problem",
        code="def knapsack(values, weights, capacity):\n    n = len(values)\n    dp = [[0] * (capacity + 1) for _ in range(n + 1)]\n    for i in range(1, n + 1):\n        for w in range(1, capacity + 1):\n            if weights[i-1] <= w:\n                dp[i][w] = max(dp[i-1][w], values[i-1] + dp[i-1][w-weights[i-1]])\n            else:\n                dp[i][w] = dp[i-1][w]\n    return dp[n][capacity]",
        intermediate_outputs=[
            "Test case 1 passed with score 0.8",
            "Test case 2 failed due to timeout",
            "Test case 3 passed with score 0.9"
        ],
        intermediate_metrics=[
            {"accuracy": 0.8, "speed": 2.0},
            {"accuracy": 0.0, "speed": 10.0},
            {"accuracy": 0.9, "speed": 1.5}
        ],
        intermediate_features=[
            (8, 15, 3),
            (0, 25, 1),
            (9, 18, 4)
        ],
        intermediate_scores=[0.8, 0.0, 0.9],
        intermediate_actions=[
            "Increased timeout limit",
            "Added edge case handling",
            "Optimized inner loop"
        ],
        metrics={"accuracy": 0.92, "speed": 1.23},
        features=(10, 20, 5),
        score=0.85,
        summary="Good solution with high accuracy but could be optimized for speed"
    )
    print(str(test_solution))
    print("-" * 50)
    print("\n1.2 Testing intermediate experiment results:")
    print(test_solution.experiment_history())
    print("-" * 50)
    #print("\n1.3 Testing Solution detailed_str property:")
    #print(test_solution.detailed_str)
    #print("-" * 50)
    

    # Test extract_python_code
    print("\n2. Testing extract_python_code:")
    test_text_with_code = """
Here is some explanation:
```python
def hello():
    print("Hello, world!")
    return 42
```
And some more text.
"""
    extracted_code = extract_python_code(test_text_with_code)
    print(f"Input text: {test_text_with_code[:50]}...")
    print(f"Extracted code: {extracted_code}")

    test_text_no_code = "Just plain text without code blocks"
    extracted_none = extract_python_code(test_text_no_code)
    print(f"Input without code blocks: {test_text_no_code}")
    print(f"Result: {extracted_none}")
    print("-" * 50)

    # Test extract_json on list and dict json strings
    print("\n3. Testing extract_json:")

    # Test with dict JSON
    dict_json = '{"name": "Alice", "age": 30, "city": "New York"}'
    dict_result = extract_json(dict_json)
    print(f"Dict JSON input: {dict_json}")
    print(f"Dict result: {dict_result}")
    print(f"Type: {type(dict_result)}")

    # Test with list JSON
    list_json = '[1, 2, 3, "four", {"nested": "object"}]'
    list_result = extract_json(list_json)
    print(f"\nList JSON input: {list_json}")
    print(f"List result: {list_result}")
    print(f"Type: {type(list_result)}")

    # Test with markdown code blocks
    json_with_markdown = '```json\n{"key": "value", "array": [1, 2, 3]}\n```'
    markdown_result = extract_json(json_with_markdown)
    print(f"\nJSON with markdown input: {json_with_markdown}")
    print(f"Markdown result: {markdown_result}")
    print(f"Type: {type(markdown_result)}")
    print("-" * 50)

    # Test parents_to_str
    print("\n4. Testing parents_to_str:")

    parent1 = Solution(
        idea="Parent idea 1",
        code="def parent1(): pass",
        intermediate_actions=["Action 1", "Action 2"],
        score=0.7
    )

    parent2 = Solution(
        idea="Parent idea 2",
        code="def parent2(): return 42",
        intermediate_actions=["Action A", "Action B"],
        score=0.8
    )

    # Test with single parent
    single_parent_str = parents_to_str(parent1)
    print(f"Single parent result:\n{single_parent_str}")

    # Test with list of parents
    parents_list_str = parents_to_str([parent1, parent2])
    print(f"\nMultiple parents result:\n{parents_list_str}")

    # Test with None
    none_parents_str = parents_to_str(None)
    print(f"\nNone input result: '{none_parents_str}'")
    print("-" * 50)

    # Test file_to_string (create a test file)
    print("\n5. Testing file_to_string:")
    test_file_path = "test_utils_temp.txt"
    try:
        with open(test_file_path, "w") as f:
            f.write("This is a test file.\nLine 2\nLine 3")

        file_content = file_to_string(test_file_path)
        print(f"File content read: {file_content}")

        # Clean up
        import os
        os.remove(test_file_path)
        print("Test file cleaned up.")
    except Exception as e:
        print(f"Error in file_to_string test: {e}")

    # Test LLM client (mock test - doesn't make actual API calls)
    print("\n6. Testing LLM client structure:")
    # Test client initialization
    client = LLMClient()
    print(f"LLMClient initialized with provider: {client.llm_provider}")
    print(f"Model name: {client.model_name}")
    print(f"Max retries: {client.max_tries}")
    messages = [{"role": "user", "content": "hello"}]
    response = client.chat(messages=messages)
    print(response)

    
    # Test update_parameter() and update_code() methods
    print("\n=== Testing update_parameter() ===")
    test_code = '''def example_function():
    a = 1.0
    b = 2.0
    c = 3.0
    return a + b + c'''

    # Test parameter update
    parameter_definitions = "a = 1.5\nb = 2.5"
    updated_code = update_parameter(test_code, parameter_definitions)
    print("Original code:")
    print(test_code)
    print("\nUpdated code:")
    print(updated_code)

    print("\n=== Testing update_code() ===")
    # Test code update with conflict markers
    test_code2 = '''def driving_actions(edge_info, vehicles_info):
    """Generate driving actions for vehicles on the specified road segment."""
    actions = []

    # Basic implementation - each vehicle maintains current speed and doesn't change lanes
    for vehicle in vehicles_info:
        actions.append({
            'veh_id': vehicle['veh_id'],
            'acceleration': 0.0,  # Maintain current speed
            'lane_changing': 0    # No lane change
        })

    return actions'''

    code_diff = '''<<<<<<< SEARCH
    # Basic implementation - each vehicle maintains current speed and doesn't change lanes
    for vehicle in vehicles_info:
        actions.append({
            'veh_id': vehicle['veh_id'],
            'acceleration': 0.0,  # Maintain current speed
            'lane_changing': 0    # No lane change
        })
=======
    # Improved implementation - vehicles adjust speed based on traffic
    for vehicle in vehicles_info:
        actions.append({
            'veh_id': vehicle['veh_id'],
            'acceleration': 0.1,  # Slight acceleration
            'lane_changing': 0    # No lane change
        })
>>>>>>> REPLACE'''

    updated_code2 = update_code(test_code2, code_diff)
    print("Original code:")
    print(test_code2)
    print("\nUpdated code:")
    print(updated_code2)

    # Test for recursive replacement bug fix
    print("\n=== Testing recursive replacement fix ===")
    test_code3 = '''def func1():
    return "hello"

def func2():
    return "hello"

def func3():
    return "hello"'''

    code_diff2 = '''<<<<<<< SEARCH
    return "hello"
=======
    return "world"
>>>>>>> REPLACE'''

    updated_code3 = update_code(test_code3, code_diff2)
    print("Original code (3 functions with same return):")
    print(test_code3)
    print("\nUpdated code (should only replace first occurrence):")
    print(updated_code3)

    print("\n=== Testing completed ===")

    # Exit after tests to avoid running full experiment
    #import sys
    #sys.exit(0)
    
    
    
    print("\n=== All tests completed ===")


