algorithm: oragent
autosave_interval_minutes: 180
database:
  cluster_sampling_temperature_init: 1.0
  cluster_sampling_temperature_period: 10
  num_islands: 4
  reset_period_minutes: 180
elitist_as_root_period: 11
elitist_enlargement_factor: 5.0
evaluation:
  eval_env_vars: null
  python_path:
    liuqi: /opt/anaconda3/envs/sumo/bin/python
    u23310103: /share/home/u23310103/.conda/envs/sumo/bin/python
  timeout_seconds: 300
evaluation_description_disabled: false
experiment:
  function_to_evolve: heuristics
  obj_type: max
fast_exploration_for_crossover: false
ideas_coordinated_generation_disabled: false
init_pop_size: 20
max_debug_rounds: 2
max_evolutions: 500
max_experiment_repeats: 4
max_research_rounds: 10000
max_tree_depth: 1
model:
  code_agent_llm_provider: qwen
  code_agent_model_name: qwen3-coder-plus
  experiment_agent_reflect_llm_provider: qwen
  experiment_agent_reflect_model_name: qwen3-coder-plus
  experiment_agent_summarize_llm_provider: qwen
  experiment_agent_summarize_model_name: qwen3-max
  idea_agent_llm_provider: qwen
  idea_agent_model_name: qwen3-max
  idea_agent_temperature: 1.3
  lead_agent_llm_provider: qwen
  lead_agent_model_name: qwen3-max
  llm_provider: qwen
  max_retries: 10
  model_name: qwen3-coder-plus
  reevo_crossover_llm_provider: qwen
  reevo_crossover_model_name: qwen3-coder-plus
  reevo_generator_llm_provider: qwen
  reevo_generator_model_name: qwen3-coder-plus
  reevo_generator_temperature: 1.0
  reevo_long_reflector_llm_provider: qwen
  reevo_long_reflector_model_name: qwen3-coder-plus
  reevo_mutation_llm_provider: qwen
  reevo_mutation_model_name: qwen3-coder-plus
  reevo_short_reflector_llm_provider: qwen
  reevo_short_reflector_model_name: qwen3-coder-plus
  temperature: 1.0
mutation_rate: 0.5
num_children: 1
num_lead_agents: 1
num_parents: 2
output_dir: outputs/oragent/mkp_aco/imitate_reevo7
pop_size: 10
problem: mkp_aco
reflection_clearance_period: null
reflection_compression: null
reflection_disabled_for_crossover: false
reflection_elitist_synchro: true
reflection_period: 0
verbose: true
